/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/6.8.3/samples
 */


plugins {
    java
    `maven-publish`
    application
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://csspeechstorage.blob.core.windows.net/maven/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.microsoft.cognitiveservices.speech:client-sdk:1.17.0")
    implementation("com.google.code.gson:gson:2.8.5")
    implementation("com.squareup.okhttp:okhttp:2.5.0")
}

group = "com.microsoft.cognitiveservices.speech.samples"
version = "0.0.1-SNAPSHOT"
description = "quickstart"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

application {
    mainClass.set("src.speechsdk.quickstart.Main")
}

